{{- if .Values.influx.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb-stats-exporter.fullname" . }}-secret
  labels:
    app: {{ include "influxdb-stats-exporter.name" . }}
    chart: {{ include "influxdb-stats-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  {{- if .Values.influx.auth.user }}
  user: {{ .Values.influx.auth.user }} 
  {{- end }}
  {{- if .Values.influx.auth.user }}
  password: {{ .Values.influx.auth.password }} 
  {{- end }}
{{- end }}
